const AU_TO_SCENE_UNITS = 90;
const SCENE_UNITS_TO_AU = 1 / AU_TO_SCENE_UNITS;
const KILOMETERS_PER_ASTRONOMICAL_UNIT = 149_597_870.7;
const KILOMETERS_PER_SCENE_UNIT = KILOMETERS_PER_ASTRONOMICAL_UNIT * SCENE_UNITS_TO_AU;

const FRAMES_PER_SECOND = 60;
const SIMULATION_SECONDS_PER_DAY = 2.5;
const FRAMES_PER_SIMULATION_DAY = FRAMES_PER_SECOND * SIMULATION_SECONDS_PER_DAY;
const SECONDS_PER_EARTH_DAY = 86_400;
const SECONDS_PER_FRAME = SECONDS_PER_EARTH_DAY / FRAMES_PER_SIMULATION_DAY;

export {
  AU_TO_SCENE_UNITS,
  SCENE_UNITS_TO_AU,
  KILOMETERS_PER_ASTRONOMICAL_UNIT,
  KILOMETERS_PER_SCENE_UNIT,
  FRAMES_PER_SECOND,
  SIMULATION_SECONDS_PER_DAY,
  FRAMES_PER_SIMULATION_DAY,
  SECONDS_PER_EARTH_DAY,
  SECONDS_PER_FRAME
};
